apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJiYXNpdDE4OSIsInBhc3N3b3JkIjoiUGFzc3cwcmRAMTIzIiwiYXV0aCI6IlltRnphWFF4T0RrNlVHRnpjM2N3Y21SQU1USXoifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: basit-reg-secret
type: kubernetes.io/dockerconfigjson
