apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhc2h1dG9zaGguYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6ImFzaHV0b3NoaCIsInBhc3N3b3JkIjoiUDZ5UDhFdHpvSUs5RFBlbXRrMUJ1TFBWQ0hqS3N1M3Zldno0SEFDUW0zK0FDUkNBWS8zNiIsImF1dGgiOiJZWE5vZFhSdmMyaG9PbEEyZVZBNFJYUjZiMGxMT1VSUVpXMTBhekZDZFV4UVZrTklha3R6ZFROMlpYWjZORWhCUTFGdE15dEJRMUpEUVZrdk16WT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: ashu-reg-secret
type: kubernetes.io/dockerconfigjson
