apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc1
spec:
  storageClassName: manual 
  accessModes:
    - ReadWriteOnce  # Must match the access mode of the PV
  resources:
    requests:
      storage: 2Gi  # Must match the storage size of the PV
