apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashuweb
  name: webslb1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ashuweb
  type: NodePort
status:
  loadBalancer: {}
