apiVersion: v1
kind: ReplicationController
metadata:
  name: ashurc1
  labels:
    x1: helloashu
spec:
  replicas: 1 # number of pods 
  selector: # so that rc can give and match label to pod 
    x1: helloashu
  template: 
    metadata:
      labels:
        x1: helloashu 
    spec:
      containers: 
      - name: ashuc1 
        image: nginx
        ports:
        - containerPort: 80