apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashupod1
  name: ashupod1 # name of pod 
spec:
  containers:
  - image: ngnix # image from docker hub 
    name: ashupod1 # container name 
    ports:
    - containerPort: 80 # applicatin pod 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
