version: "3.8"
volumes: # create volume 
  ashudbvol8:  # name of volume 
services:
  ashudb: 
    image: mysql 
    container_name: ashudbc1 
    environment:
      MYSQL_ROOT_PASSWORD: Root@0987
    volumes: # mounting volume 
    - ashudbvol8:/var/lib/mysql/
  webaapp:
    image: adminer 
    container_name: ashuwebc1 
    ports:
    - 1133:8080 
    depends_on:
    - ashudb 
  ashuwebcode:
    image: nginx 
    container_name: ashuwebc12 
    ports:
    - 4455:80 
    volumes:
    - ./html-sample-app:/usr/share/nginx/html/:ro 
  