apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashuapp
  name: ashuapp # name of deployment 
spec:
  replicas: 2 # number of pods 
  selector:
    matchLabels:
      app: ashuapp # label of pods 
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashuapp # label of pods 
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
